# Generated by Django 6.0.2 on 2026-03-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('event', '0002_alter_event_event_date'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBooking',
            new_name='booking',
        ),
    ]
