# Generated by Django 6.0.2 on 2026-03-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orginizer', '0001_initial'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_tickets', models.IntegerField()),
                ('orginizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orginizer.orginizer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue')),
            ],
        ),
    ]
